apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cicd-proj-deployment
spec:
  selector:
    matchLabels:
      app: farhaan-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: farhaan-devops-project
    spec:
      containers:
      - name: farhaan-devops-project
        image: farhaanshamsee/simple-devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
