---
- name: create service for deployment
  hosts: kubernetes
  become: true
  user: ubuntu

  tasks:
  - name: create a service
    command: kubectl --kubeconfig=/home/ubuntu/.kube/config apply -f CICD-proj-serv.yml

